
name: SonarQube Scan

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  sonarqube_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Make sure you have added the SonarQube token as a secret in your GitHub repository settings

      - name: Extract SonarQube Analysis Summary
        id: extract_summary
        run: echo "::set-output name=summary::$(cat ${GITHUB_WORKSPACE}/.scannerwork/report-task.txt | grep 'ceTaskUrl=' | sed 's/ceTaskUrl=/[SonarQube Analysis](''/' | sed 's/$/'')/')"

      - name: Create Check
        uses: actions/github-script@0.9.0
        with:
          script: |
            const summary = '${{ steps.extract_summary.outputs.summary }}';
            const { data: check } = await github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'SonarQube Scan',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'SonarQube Scan',
                summary: summary,
              },
            });
            console.log(`Check created: ${check.html_url}`);
          env:
            GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
