name: SonarQube Scan

on:
  pull_request:
    types: [opened]

jobs:
  sonarqube_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: SonarQube Scan
        run: |
          # Replace these commands with the ones appropriate for your project
          # Example commands for a Gradle project:
          sonar-scanner \
            -Dsonar.host.url=http://43.204.140.100:9000 \
            -Dsonar.login=sqp_d2770241c77b4d75ede1cdec99de39bda60acec8 \
            -Dsonar.projectKey=simple
